---
apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  labels:
    app: quirky-query
  name: quirky-query
spec:
  containers:
  - name: app
    image: quirky-query:local
    args:
    - -v
    env:
      - name: FQDN
        value: quirky-query.rwxd.de
      - name: WS_SECURE
        value: "TRUE"
    volumeMounts: []
  volumes: []
